import { K } from './def-helpers.mjs';

/** First 10 category pillars (post–construction/ag/forestry) — see CURSOR_BUILD_ALL.md */
export const DEFS_BASE = [
  {
    file: 'medical-dental-equipment-financing.html',
    title: 'Medical & Dental Equipment Financing | MRI, CT, Dental, Surgical — All Brands',
    meta: 'Financing for MRI, CT, dental chairs, surgical robotics, and imaging. Certificate of Need (CON) laws, OEM programs, and practice lenders explained.',
    h1: 'Medical &amp; Dental Equipment Financing',
    quickAnswer:
      'Medical equipment financing covers MRI systems ($300K–$3.5M), CT scanners ($80K–$2.5M), dental equipment ($5K–$200K per unit), and surgical robots ($500K–$3M). Certificate of Need (CON) laws in many states regulate high-end imaging purchases. Siemens Healthineers (Erlangen, Germany), GE Healthcare (Chicago, Illinois), and Philips (Amsterdam, Netherlands) dominate imaging.',
    keyFacts: [
      K('MRI range', '$300K–$3.5M'),
      K('CT range', '$80K–$2.5M'),
      K('Dental chair', '$5K–$35K'),
      K('CON states', '35 (imaging)'),
      K('Terms', '48–84 mo'),
      K('Top brands', 'Siemens, GE, Philips'),
    ],
    speakable: true,
    def: 'covers diagnostic imaging, dental operatories, sterilization, and surgical platforms. Underwriting may review payer mix, CON approvals, and service contract costs.',
    detail:
      'Imaging deals often include service contracts in total cost of ownership. Compare mri-machine-financing and review state CON requirements before committing.',
    links: [
      ['mri-machine-financing.html', 'MRI machine financing'],
      ['equipment-financing-credit-requirements.html', 'credit requirements'],
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['financing-unknown-equipment-brands.html', 'lesser-known brands'],
      ['equipment-business-licensing-requirements.html', 'licensing hub'],
      ['all-commercial-equipment.html', 'equipment directory'],
    ],
  },
  {
    file: 'food-processing-equipment-financing.html',
    title: 'Food Processing Equipment Financing | Commercial Kitchen, Industrial Processing & Packaging',
    meta: 'Financing for ovens, mixers, packaging lines, refrigeration, and full processing plants. FDA registration, NSF equipment, and lender requirements.',
    h1: 'Food Processing Equipment Financing',
    quickAnswer:
      'Food processing equipment financing covers commercial ovens ($5K–$100K), industrial mixers ($5K–$100K), packaging lines ($20K–$500K+), and complete systems. FDA food facility registration applies to processors. Hobart (Troy, Ohio), Vulcan, Manitowoc Ice, True Manufacturing, and Multivac are widely recognized by lenders.',
    keyFacts: [
      K('Ovens', '$5K–$100K'),
      K('Packaging line', '$20K–$500K+'),
      K('Terms', '36–72 mo'),
      K('NSF', 'Often required'),
      K('FDA', 'Facility registration'),
      K('Brands', 'Hobart, Vulcan, True'),
    ],
    speakable: true,
    def: 'is production equipment subject to food safety plans, sanitary design, and often NSF listings. Lenders review tenant improvements and cash flow from contracts.',
    links: [
      ['restaurant-equipment-financing.html', 'restaurant equipment financing'],
      ['warehouse-material-handling-financing.html', 'material handling'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['equipment-financing-for-startups.html', 'startup financing'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['all-commercial-equipment.html', 'directory'],
      ['equipment-business-licensing-requirements.html', 'business licensing'],
    ],
  },
  {
    file: 'warehouse-material-handling-financing.html',
    title: 'Warehouse & Material Handling Equipment Financing | Forklifts, Conveyors, Racking & ASRS',
    meta: 'Financing for forklifts, conveyors, pallet racking, automated storage, and dock equipment. OSHA forklift certification, Toyota, Crown, Raymond.',
    h1: 'Warehouse &amp; Material Handling Equipment Financing',
    quickAnswer:
      'Warehouse equipment financing covers forklifts ($15K–$100K), conveyor systems ($10K–$1M+), pallet racking ($5K–$500K), and automated storage ($200K–$5M+). OSHA requires forklift operator certification under 29 CFR 1910.178 before operation. Toyota (Columbus, Indiana assembly), Crown Equipment, and Raymond (Toyota group) are highly financeable.',
    keyFacts: [
      K('Electric forklift', '$24K–$85K'),
      K('Reach truck', '$15K–$55K'),
      K('Conveyors', '$10K–$1M+'),
      K('OSHA', '1910.178 training'),
      K('Terms', '36–72 mo'),
      K('Brands', 'Toyota, Crown, Raymond'),
    ],
    speakable: true,
    def: 'includes lift trucks, conveyors, racking, and automation that moves inventory. Collateral value depends on truck hours, battery health, and mast configuration.',
    detail: 'See forklift-financing for model-level detail and toyota-forklift-financing for OEM programs.',
    links: [
      ['forklift-financing.html', 'forklift financing'],
      ['toyota-forklift-financing.html', 'Toyota forklift financing'],
      ['equipment-financing-vs-lease.html', 'lease vs loan'],
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['all-commercial-equipment.html', 'directory'],
      ['warehouse-material-handling-financing.html', 'this category overview'],
    ],
  },
  {
    file: 'printing-signage-equipment-financing.html',
    title: 'Printing & Signage Equipment Financing | Wide Format, Digital Presses, Screen Printing',
    meta: 'Financing for wide format printers, digital presses, screen printing, finishing, and cutters. HP, Epson, Roland, Heidelberg. EPA air permits for solvents.',
    h1: 'Printing &amp; Signage Equipment Financing',
    quickAnswer:
      'Printing equipment financing covers wide format printers ($5K–$100K), digital production presses ($50K–$500K), offset presses ($50K–$1M+), and screen printing ($5K–$100K). HP, Epson, Roland DG, Mimaki, and Heidelberg are familiar to lenders. Solvent and UV operations may need EPA or state air quality permits.',
    keyFacts: [
      K('Wide format', '$5K–$100K'),
      K('Digital press', '$50K–$500K'),
      K('Offset', '$50K–$1M+'),
      K('Permits', 'Air quality (solvent)'),
      K('Terms', '36–72 mo'),
      K('Brands', 'HP, Epson, Roland'),
    ],
    speakable: true,
    def: 'covers imaging devices that produce graphics, packaging, and commercial print. Residual values track technology obsolescence faster than machine tools.',
    links: [
      ['wide-format-printer-financing.html', 'wide format printer financing'],
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['equipment-financing-for-startups.html', 'startup financing'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['financing-unknown-equipment-brands.html', 'obscure brands'],
      ['all-commercial-equipment.html', 'directory'],
      ['equipment-financing-credit-requirements.html', 'credit'],
    ],
  },
  {
    file: 'restaurant-equipment-financing.html',
    title: 'Restaurant Equipment Financing | Full Kitchen Buildouts, Individual Pieces — All Brands',
    meta: 'Financing for line equipment, refrigeration, exhaust, and full buildouts. Health department permits, NSF listings, and down payment expectations.',
    h1: 'Restaurant Equipment Financing',
    quickAnswer:
      'Restaurant equipment financing covers full kitchen buildouts ($30K–$500K), individual commercial pieces, and startup packages. Health department food service permits and NSF listings apply. Vulcan, Hobart, True, and Hoshizaki are widely recognized. New restaurants often need 20–30% down.',
    keyFacts: [
      K('Buildout', '$30K–$500K'),
      K('Walk-in cooler', '$8K–$45K'),
      K('Down (startup)', '20–30%'),
      K('NSF', 'Typical requirement'),
      K('Terms', '36–72 mo'),
      K('Brands', 'Vulcan, Hobart, True'),
    ],
    speakable: true,
    def: 'is commercial cooking, holding, and refrigeration equipment purchased for foodservice operations. Underwriters review operator experience, location, and pro forma sales.',
    links: [
      ['food-processing-equipment-financing.html', 'food processing equipment'],
      ['equipment-financing-for-startups.html', 'startup financing'],
      ['equipment-financing-down-payment.html', 'down payments'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['all-commercial-equipment.html', 'directory'],
      ['equipment-financing-credit-requirements.html', 'credit'],
    ],
  },
  {
    file: 'hvac-equipment-financing.html',
    title: 'Commercial HVAC Equipment Financing | Rooftop Units, Chillers, Boilers — All Brands',
    meta: 'Financing for RTUs, chillers, boilers, cooling towers, and VRF. EPA 608 technician rules, state contractor licensing, Carrier, Trane, York, Daikin.',
    h1: 'Commercial HVAC Equipment Financing',
    quickAnswer:
      'Commercial HVAC equipment financing covers rooftop units ($5K–$150K per unit), chillers ($100K–$2M), and boilers ($20K–$500K). EPA Section 608 certification is mandatory for technicians handling refrigerants. State HVAC contractor licenses are common. Carrier (Palm Beach Gardens, Florida), Trane (Davidson, North Carolina), York, and Daikin are financeable brands.',
    keyFacts: [
      K('RTU', '$5K–$150K'),
      K('Chiller', '$100K–$2M'),
      K('EPA 608', 'Required'),
      K('Terms', '36–120 mo'),
      K('Install', 'Often bundled'),
      K('Brands', 'Carrier, Trane, Daikin'),
    ],
    speakable: true,
    def: 'covers heating, cooling, and ventilation assets tied to buildings. Financing may include installation and controls; collateral is the equipment on site.',
    links: [
      ['equipment-business-licensing-requirements.html', 'business licensing'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['equipment-financing-vs-lease.html', 'lease vs loan'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['all-commercial-equipment.html', 'directory'],
      ['equipment-financing-credit-requirements.html', 'credit'],
      ['equipment-financing-for-startups.html', 'startups'],
    ],
  },
  {
    file: 'oil-gas-equipment-financing.html',
    title: 'Oil & Gas Equipment Financing | Pumping Units, Compressors, Separators — All Brands',
    meta: 'Financing for beam pumps, compressors, separators, tanks, and wellhead equipment. API specs, state commissions, PHMSA pipeline rules.',
    h1: 'Oil &amp; Gas Equipment Financing',
    quickAnswer:
      'Oil and gas equipment financing covers pumping units ($30K–$300K), gas compressors ($50K–$2M+), separators ($20K–$500K), and drilling packages ($500K–$10M+). API specifications and state oil & gas commission permits apply. NOV (NOV Inc., Houston, Texas), Ariel Corporation (Mount Vernon, Ohio), and Gardner Denver are leading suppliers.',
    keyFacts: [
      K('Pumpjack', '$30K–$300K'),
      K('Compressor', '$50K–$2M+'),
      K('Separator', '$20K–$500K'),
      K('Regulatory', 'State + PHMSA'),
      K('Terms', '36–84 mo'),
      K('Brands', 'NOV, Ariel, GD'),
    ],
    speakable: true,
    def: 'is production and midstream equipment for hydrocarbon extraction and handling. Financing sensitivity tracks commodity prices and operator cash flow.',
    links: [
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['equipment-financing-credit-requirements.html', 'credit'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['equipment-financing-after-bankruptcy.html', 'credit events'],
      ['all-commercial-equipment.html', 'directory'],
      ['mining-equipment-financing.html', 'mining equipment'],
      ['equipment-business-licensing-requirements.html', 'licensing'],
    ],
  },
  {
    file: 'mining-equipment-financing.html',
    title: 'Mining Equipment Financing | Drills, Crushers, Conveyors, Haul Trucks — All Brands',
    meta: 'Financing for drills, crushers, screens, conveyors, and haul trucks. MSHA compliance, Caterpillar, Komatsu Mining, Sandvik, Epiroc.',
    h1: 'Mining Equipment Financing',
    quickAnswer:
      'Mining equipment financing covers surface drill rigs ($200K–$2M), crushers ($50K–$2M), haul trucks ($300K–$5M+), and longwall systems ($5M–$50M+). MSHA training and mine plans are federally required. Caterpillar (Peoria, Illinois), Komatsu, Sandvik (Stockholm, Sweden), and Epiroc dominate supply.',
    keyFacts: [
      K('Drill rig', '$200K–$2M'),
      K('Haul truck', '$300K–$5M+'),
      K('MSHA', 'Required'),
      K('Terms', '48–120 mo'),
      K('Down', '10–25%'),
      K('Brands', 'Cat, Komatsu, Sandvik'),
    ],
    speakable: true,
    def: 'is heavy equipment for extraction, sizing, and transport of minerals. Deals are collateral-heavy and often require project or contract visibility.',
    links: [
      ['caterpillar-equipment-financing.html', 'Caterpillar financing'],
      ['komatsu-equipment-financing.html', 'Komatsu financing'],
      ['excavator-financing.html', 'excavator financing'],
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['equipment-financing-credit-requirements.html', 'credit'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['all-commercial-equipment.html', 'directory'],
      ['american-vs-asian-equipment-financing.html', 'brand resale'],
    ],
  },
  {
    file: 'gym-fitness-equipment-financing.html',
    title: 'Commercial Gym & Fitness Equipment Financing | Cardio, Strength & Complete Buildouts',
    meta: 'Financing for treadmills, strength lines, flooring, and full gym packages. Life Fitness, Precor, Technogym, Matrix.',
    h1: 'Commercial Gym &amp; Fitness Equipment Financing',
    quickAnswer:
      'Commercial gym equipment financing covers treadmills ($3K–$15K each), strength systems ($5K–$50K per station), and complete buildouts ($50K–$500K+). Life Fitness (Rosemont, Illinois), Precor, Technogym, and Matrix are recognized brands. Typical terms are 36–60 months with 10–15% down.',
    keyFacts: [
      K('Treadmill', '$3K–$15K'),
      K('Full gym', '$50K–$500K+'),
      K('Terms', '36–60 mo'),
      K('Down', '10–15%'),
      K('Credit', '620+ typical'),
      K('Brands', 'Life Fitness, Precor'),
    ],
    speakable: true,
    def: 'is cardio, strength, and accessory equipment for member-based fitness businesses. Underwriters review membership sales history and location demographics.',
    links: [
      ['equipment-financing-for-startups.html', 'startup financing'],
      ['equipment-financing-down-payment.html', 'down payments'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['lease-vs-loan-equipment.html', 'lease vs loan'],
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['all-commercial-equipment.html', 'directory'],
      ['equipment-financing-credit-requirements.html', 'credit'],
    ],
  },
  {
    file: 'laundry-equipment-financing.html',
    title: 'Commercial Laundry Equipment Financing | Washers, Dryers, Dry Cleaning — All Brands',
    meta: 'Financing for washers, dryers, tunnel systems, and PERC dry cleaning. EPA PERC rules, Speed Queen, Milnor, Electrolux Professional.',
    h1: 'Commercial Laundry Equipment Financing',
    quickAnswer:
      'Commercial laundry equipment financing covers industrial washers ($5K–$200K), dryers ($3K–$100K), dry cleaning machines ($20K–$150K), and tunnel systems ($500K–$3M). EPA regulations on perchloroethylene require air permits for many dry cleaners. Speed Queen, Milnor, and Electrolux Professional lead the market.',
    keyFacts: [
      K('Washer', '$5K–$200K'),
      K('Dry cleaning', '$20K–$150K'),
      K('Tunnel line', '$500K–$3M'),
      K('EPA', 'PERC rules'),
      K('Terms', '36–84 mo'),
      K('Brands', 'Speed Queen, Milnor'),
    ],
    speakable: true,
    def: 'is washing, drying, and finishing equipment for laundries, hospitality, and healthcare linens. Real estate and utility commitments affect underwriting.',
    links: [
      ['how-commercial-equipment-financing-works.html', 'how financing works'],
      ['equipment-financing-credit-requirements.html', 'credit'],
      ['new-vs-used-equipment-financing.html', 'new vs used'],
      ['section-179-equipment-deduction.html', 'Section 179'],
      ['equipment-financing-for-startups.html', 'startups'],
      ['all-commercial-equipment.html', 'directory'],
      ['equipment-business-licensing-requirements.html', 'licensing'],
      ['food-processing-equipment-financing.html', 'industrial processing'],
    ],
  },
];
